module Match3.Core
  ( Color(..)
  , GemKind(..)
  , Cell(..)
  , mkGem
  , Pos
  , Board
  , boardSize
  , numColors
  , allColors
  , Score
  , MovesLeft
  , TargetScore
  , Outcome(..)
  , LevelGoal(..)
  , goalMet
  , goalProgress
  , goalTarget
  , GameConfig(..)
  , defaultConfig
  , Level(..)
  , allLevels
  , levelConfig
  , getCell
  , setCell
  , swapCells
  , inBounds
  , adjacent
  , findMatches
  , findMatchRuns
  , hasAnyMatch
  , hasValidMove
  , stepCascade
  , runCascade
  , runCascadeAt
  , runCascadeScored
  , randomBoard
  , randomStableBoard
  , randomPlayableBoard
  , shufflePlayable
  , scoreForCleared
  , scoreForWave
  , findHint
  , MatchRun(..)
  , countColor
  , GameState(..)
  , newGame
  , newGameAtLevel
  , trySwap
  , runMove
  , restart
  , restartLevel
  , checkOutcome
  , undoMove
  , applyHint
  , nextLevel
  , ensurePlayable
  , shuffleGame
  ) where

import Match3.Board
import Match3.Game
import Match3.Types
