-- | 库门面：再导出 Types、Board.* / Game.* 子模块与各机制模块的稳定公开 API（给前端用）。
-- 自身几乎无业务逻辑；前端与测试应优先 import Match3.Core。
-- 不拥有：SDL、关卡装饰布局细节（在 Game）、连锁波次实现（在 Board）。
module Match3.Core
  ( Color(..)
  , GemKind(..)
  , CellContents(..)
  , Cell
  , ElementName(..)
  , CustomState(..)
  , mkGem
  , mkIceGem
  , iceLayers
  , specialActivates
  , chipIceOnClear
  , CellOverlay(..)
  , mkGrassGem
  , mkVineGem
  , mkChocoGem
  , hasGrass
  , hasVine
  , hasChoco
  , hasFog
  , fogLayers
  , mkFogGem
  , hasChain
  , chainLayers
  , mkChainGem
  , hasFreeze
  , freezeLayers
  , mkFreezeGem
  , hasCurtain
  , curtainLayers
  , mkCurtainGem
  , mkSnail
  , isSnail
  , snailDir
  , mkSafe
  , mkSafeLayers
  , safeLayers
  , isSafe
  , mkFlip
  , isFlip
  , flipFront
  , flipBack
  , mkSurprise
  , isSurprise
  , mkBottle
  , isBottle
  , bottleColor
  , mkTimeSpirit
  , isTimeSpirit
  , mkSteamGem
  , hasSteam
  , cellOverlay
  , clearOverlaysOn
  , clearChocoAdjacent
  , clearSteamAdjacent
  , chipAdjacentFog
  , chipAdjacentChain
  , chipAdjacentFreeze
  , chipAdjacentCurtain
  , vinePositions
  , chocoPositions
  , chainPositions
  , freezePositions
  , curtainPositions
  , steamPositions
  , spreadVines
  , spreadChoco
  , spreadSteam
  , coverCarpets
  , levelCarpets
  , stepSnails
  , stepSnailsAvoiding
  , stepSnailsAvoidingBlocked
  , stepSnailAt
  , stepSnailAtBlocked
  , snailPositions
  , Ufo(..)
  , mkUfo
  , ufoAbsorbTargets
  , moveUfo
  , stepUfo
  , stepUfos
  , mkStone
  , mkStoneLayers
  , stoneLayers
  , isStone
  , mkChest
  , mkChestLayers
  , chestLayers
  , isChest
  , mkHoney
  , mkHoneyLayers
  , honeyLayers
  , isHoney
  , mkBalloon
  , isBalloon
  , balloonColor
  , mkCookie
  , isCookie
  , mkCake
  , mkCakeLayers
  , cakeLayers
  , isCake
  , mkMagicHat
  , isMagicHat
  , mkMaker
  , mkMakerCharges
  , makerColor
  , makerCharges
  , isMaker
  , mkCountdown
  , isCountdown
  , countdownTurns
  , spawnCountdown
  , tickCountdowns
  , countdownsAtZero
  , explodeRadius
  , explodeSeedsFor
  , Belt
  , shiftBelt
  , shiftBelts
  , isGem
  , cellColor
  , cellKind
  , Pos
  , Board
  , boardFromRows
  , boardRows
  , boardCells
  , boardAssocs
  , mapBoard
  , boardSize
  , numColors
  , allColors
  , colorAt
  , Score
  , MovesLeft
  , TargetScore
  , Outcome(..)
  , LevelGoal(..)
  , Meter(..)
  , Quota(..)
  , goalScore
  , goalCollect
  , goalColors
  , goalCount
  , GoalView(..)
  , goalView
  , meterValue
  , goalMet
  , goalProgress
  , goalTarget
  , GameConfig(..)
  , defaultConfig
  , Level(..)
  , level
  , allLevels
  , lookupLevel
  , levelCount
  , clampLevelIndex
  , levelConfig
  , getCell
  , setCell
  , swapCells
  , inBounds
  , adjacent
  , findMatches
  , findMatchRuns
  , hasAnyMatch
  , hasValidMove
  , stepCascade
  , randomBoard
  , randomStableBoard
  , randomPlayableBoard
  , shufflePlayable
  , scoreForCleared
  , scoreForWave
  , findHint
  , MatchRun(..)
  , countColor
  , GameState(..)
  , gsCount
  , gsProgress
  , gsGoalMet
  , gsCollected
  , gsColorBag
  , CounterKey(..)
  , Counts
  , countOf
  , countsFromList
  , countsToList
  , namedCounts
  , colorBag
  , newGame
  , newGameAtLevel
  , campaignGame
  , newDailyGame
  , trySwap
  , MoveFx(..)
  , moveFx
  , clearMoveFx
  , MoveTrace(..)
  , EndStep(..)
  , EndEffect(..)
  , SpreadKind(..)
  , SnailMove(..)
  , applyEndEffect
  , traceSwap
  , traceFreeSwap
  , traceHammer
  , traceCrossClear
  , CascadeWave(..)
  , runMove
  , restart
  , restartLevel
  , checkOutcome
  , applyHint
  , nextLevel
  , ensurePlayable
  , shuffleGame
  , useHammer
  , useFreeSwap
  , useCrossClear
  , loseHint
  , unlockAfterClear
  , unlockAfterOutcome
  , mapClickJump
  , hammerClearSeeds
  , crossClearSeeds
  , orthoNeighbors
  , stonesAdjacentTo
  , withAdjacentStones
  , chipAdjacentStones
  , chipAdjacentChests
  , chestsAdjacentTo
  , chipAdjacentHoney
  , honeysAdjacentTo
  , chipAdjacentCakes
  , cakesAdjacentTo
  , chipAdjacentSafes
  , safesAdjacentTo
  , openAdjacentSurprises
  , openSurprises
  , surprisesAdjacentTo
  , triggerAdjacentBottles
  , triggerAdjacentBottlesExcept
  , bottlesAdjacentTo
  , spiritsAdjacentTo
  , chipAdjacentTimeSpirits
  , chipAdjacentBalloons
  , balloonsAdjacentSameColor
  , hatsAdjacentTo
  , triggerAdjacentHats
  , triggerAdjacentHatsExcept
  , makersAdjacentSameColor
  , chargeAdjacentMakers
  , chargeAdjacentMakersSit
  , applyPortalTeleports
  , settleBoardPortals
  , expandSpecials
  , isRainbow
  , isRainbowSwap
  , rainbowClearSeeds
  , isLineBombCombo
  , isRainbowLineCombo
  , isBombBombCombo
  , isLineLineCombo
  , isSpecialCombo
  , comboClearSeeds
  , dailySeed
  , dailyConfig
  , dailyLevel
  , starRating
  ) where

import Match3.Board.Default (applyPortalTeleports, countColor, expandSpecials, findHint, findMatchRuns, findMatches, hasAnyMatch, hasValidMove, settleBoardPortals, stepCascade)
import Match3.Board.Cascade (CascadeWave(..))
import Match3.Board.Clear (scoreForCleared, scoreForWave)
import Match3.Board.Grid (adjacent, getCell, inBounds, setCell, swapCells)
import Match3.Board.Match (MatchRun(..))
import Match3.Board.Random (randomBoard, randomPlayableBoard, randomStableBoard, shufflePlayable)
import Match3.Counts (CounterKey(..), Counts, colorBag, countOf, countsFromList, countsToList, namedCounts)
import Match3.Ice (chipIceOnClear)
import Match3.Grass
  ( clearOverlaysOn
  , clearChocoAdjacent
  , clearSteamAdjacent
  , chipAdjacentFog
  , chipAdjacentChain
  , chipAdjacentFreeze
  , chipAdjacentCurtain
  , vinePositions
  , chocoPositions
  , chainPositions
  , freezePositions
  , curtainPositions
  , steamPositions
  , spreadVines
  , spreadChoco
  , spreadSteam
  )
import Match3.Carpet (coverCarpets)
import Match3.Levels.Campaign (allLevels, clampLevelIndex, levelCarpets, levelCount, lookupLevel)
import Match3.Levels.Level (Level(..), level, levelConfig)
import Match3.Snail
  ( stepSnails
  , stepSnailsAvoiding
  , stepSnailsAvoidingBlocked
  , stepSnailAt
  , stepSnailAtBlocked
  , snailPositions
  )
import Match3.Ufo
  ( Ufo(..)
  , mkUfo
  , ufoAbsorbTargets
  , moveUfo
  , stepUfo
  , stepUfos
  )
import Match3.Game.Boosters
import Match3.Game.Level
import Match3.Game.Move
import Match3.Game.Outcome
import Match3.Game.Shuffle
import Match3.Game.State
import Match3.Game.Trace
import Match3.Obstacles
  ( orthoNeighbors
  , stonesAdjacentTo
  , withAdjacentStones
  , chipAdjacentStones
  , chipAdjacentChests
  , chestsAdjacentTo
  , chipAdjacentHoney
  , honeysAdjacentTo
  , chipAdjacentCakes
  , cakesAdjacentTo
  , chipAdjacentSafes
  , safesAdjacentTo
  , chipAdjacentBalloons
  , balloonsAdjacentSameColor
  , hatsAdjacentTo
  , triggerAdjacentHats
  , triggerAdjacentHatsExcept
  , makersAdjacentSameColor
  , chargeAdjacentMakers
  , chargeAdjacentMakersSit
  , openAdjacentSurprises
  , openSurprises
  , surprisesAdjacentTo
  , triggerAdjacentBottles
  , triggerAdjacentBottlesExcept
  , bottlesAdjacentTo
  , spiritsAdjacentTo
  , chipAdjacentTimeSpirits
  )
import Match3.Daily (dailySeed, dailyConfig, dailyLevel, starRating)
import Match3.Conveyor (Belt, shiftBelt, shiftBelts)
import Match3.Boosters (hammerClearSeeds, crossClearSeeds)
import Match3.Countdown
  ( spawnCountdown
  , tickCountdowns
  , countdownsAtZero
  , explodeRadius
  , explodeSeedsFor
  )
import Match3.Combos
  ( isLineBombCombo
  , isRainbowLineCombo
  , isBombBombCombo
  , isLineLineCombo
  , isSpecialCombo
  , comboClearSeeds
  )
import Match3.Rainbow
  ( isRainbow
  , isRainbowSwap
  , rainbowClearSeeds
  )
import Match3.Types
